[platformio]
default_envs = cyd
src_dir = AnalogPinScanner

[env:cyd]
platform = espressif32@6.10.0
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 115200
upload_port = /dev/cu.usbserial-210

lib_deps =
  bodmer/TFT_eSPI

build_flags =
  -D USER_SETUP_LOADED=1
  -D ILI9341_DRIVER=1
  -D TFT_WIDTH=240
  -D TFT_HEIGHT=320
  -D TFT_MISO=12
  -D TFT_MOSI=13
  -D TFT_SCLK=14
  -D TFT_CS=15
  -D TFT_DC=2
  -D TFT_RST=-1
  -D TFT_BL=21
  -D TFT_BACKLIGHT_ON=HIGH
  -D LOAD_GLCD=1
  -D SPI_FREQUENCY=40000000
  -D SPI_READ_FREQUENCY=16000000
